language: python
python:
  - 3.5
cache:
  - pip: true
before_install:
  - apt-get update
  - apt-get install -yqq apt-transport-https
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update
  - apt-get -yqq install default-jre sbt
install:
  - python setup.py build sdist
  - cd dist && pip install py4jdbc*.tar.gz
script:
  - python setup.py test
env:
  global:
    CLASSPATH: /usr/local/share/py4jdbc/py4jdbc-assembly-0.1.6.8.jar
    secure: QZtymZcUnh+oB8FgRRn3Zbi2kyqEFAfZik2t080/cKSU7iV9SjyCT9BfvotjCEDkGDtLU4yWMrnzhoPRI6Dqomn+BxK6CCYsUkeA/qcZeUA4rjdGKdXeDKh91cMsh725odKj76YQNWv1fvYiLEbiKcw4Rlzx/gxqizpOVlo+zxIqj5W3BCTukrXjIe53hypwrH5wuX5F6cEQk2/rvF0Gykx7vXbE4YhipoG0ws2KZ/KDrkIyy9in67lnQtMVN97Etj/Hz9CpFSvjCRfiIXVVi/K0UdlUQQfrPHzb/30qNi2Y1jKJCBid29NfCPx4fScxXZnKMhPeOq/j6YDHRroWcw+ppa8bFjXXWNXjYCNgxJZYSJhSxudIXMmNb48KLtvN6hVwQPAWAi5qohpHZ3DAaDu2QYCD2ErqtSttJfYrUge3q5x2pwtxSXSB8XhFqFs6B1mrmrxE/Emp5zkBb+h1qKeQuuH7gdYu7isOBTwNVwfJSt+it0lPsaJFx3UhF49wV5BmxCxtmYQC6ZZykjGwWQmEDEFO/2WYtOlgccJcLzXxzknUpi8M4LPp+mijRQmNtVmZiCf1yexL9Ebl8WhTToj4Cg54f5UbuG5HCplSFrDCHAAJHzZgHORnKE23TloALyhsrkHERJRqZ4SjMjsiIwaET34Nojc1TlN2fyov9yU=
