language: python
python:
  - 3.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -yqq apt-transport-https
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - sudo apt-get update
  - sudo apt-get -yqq install default-jre sbt
install:
  - python setup.py build sdist bdist_wheel
  - cd dist && pip install py4jdbc*.whl
script:
  - python setup.py test
env:
  - CLASSPATH=/usr/local/share/py4jdbc/py4jdbc-assembly-0.1.6.8.jar
